version: "3"
services:
  api:
    command: npm run dev
    volumes:
     - .:/app
     - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres@db/messages
      REDIS_URL: redis://cache
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: messages
